### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by ibnesayeed** [codingtwinky/atom-ungit#22]
Here is a deprecation warning in updated Atom:

atom-ungit
keymaps/ungit.cson
Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by ibnesayeed** [comment]
I see it is fixed in the code, but the code is not released yet.

**Comment by codingtwinky** [comment]
Fixed in #19 will be releasing a new tag soon.
