### ISSUE TITLE
Missing branch/tag buttons on latest commit

### ISSUE THREAD

**Issue by capaj** [codingtwinky/atom-ungit#41]
![image](https://cloud.githubusercontent.com/assets/1305378/10895228/62c970e2-81b3-11e5-8591-25870839129e.png)

I would like to branch or tag my latest commit, but I cannot see it. Shouldn't I be able to see the buttons always when selecting the latest commit?

**Comment by codingtwinky** [comment]
In the picture you have selected a checked out branch, which is master.  But if you click open spaces you should be able to see the small "+" symbol that will allows you to create a tag or branch rather then move button.

Is that what you are looking for?

**Comment by capaj** [comment]
Yes, that is what I was looking for. I guess I was just surprised by the little plus sign disappearing when selecting the branch. I can understand why they disappear when I select a branch-because `+ move` is displayed instead. But do you really have to hide it when I select the commit circle?

**Comment by codingtwinky** [comment]
Admittedly, I have UI design skill of blind orangutan so I'm open to the UI idea.  But honestly I like what we have as different state displays different ops with context.

**Comment by capaj** [comment]
@codingtwinky there is certainly an issue with "+" not being shown when it should. If I hover my mouse, there is like 1 or 2 pixels, where I can click and it works as if I clicked on "+" but the + is not visible. This is some layout issue I guess.
