### ISSUE TITLE
/bin/sh: 1: node: not found

### ISSUE THREAD

**Issue by capaj** [codingtwinky/atom-ungit#46]
I have ubuntu 15.10 and node installed with nvm and when I try to opne ungit in atom it just prints an error into the console:
```
/bin/sh: 1: node: not found
(anonymous function) @ atom-ungit.coffee:121
```
DO you know how to make it work?

**Comment by codingtwinky** [comment]
I think it is related to this issue: https://github.com/FredrikNoren/ungit/issues/381.
