### ISSUE TITLE
Cannot launch ungit

### ISSUE THREAD

**Issue by mikus** [codingtwinky/atom-ungit#48]
Pressing `ctrl-alt-u` on Ubuntu 15.10 I got new tab with following message:

```
Invalid path
"atom://.atom/init-script" doesn't seem to be a valid path.
```

**Comment by codingtwinky** [comment]
I'm little perplexed by this error message.  `.atom/init-script` is not being used or touched via ungit-atom so I think this might be a atom installation issue or config issue.

Could you possibly reinstalling atom or upgrading it first?

**Comment by mikus** [comment]
it was while ago, with current version I have no problems
