### ISSUE TITLE
Update ungit to 1.3.3

### ISSUE THREAD

**Issue by neerdoc** [codingtwinky/atom-ungit#51]
Ungit is now version 1.3.3.

I'm on Mac OS X and have installed node via homebrew. I have updated ungit locally and it is the latest version if I start it directly from the command line. But from atom I seem to get version 1.2.3 for some reason.

Any advice?

**Comment by codingtwinky** [comment]
Bumped the ungit version and published `atom-ungit@0.6.0`

cheers
